spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: future_star

# Student should config datasource here
  datasource:
    url: jdbc:mysql://localhost:3306/hello?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 50
      max-wait: 10000
      test-on-borrow: true
      initial-size: 5
      min-idle: 5
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

# Student should config security here
security:
  jwt:
    secret: ${JWT_SECRET:_SEMS_JWT_SECRET_201708240805987}
    expiration-in-seconds: 600

# Student should config flyway here
flyway:
  locations: db/migration
  enabled: true